const assert = require('node:assert/strict');
global.Measurements = require('../review_app/static/js/measurements.js');
const Workspace = require('../review_app/static/js/workspace.js');
const config = {width:6,height:4,dpi:300,orientation:'landscape',fit_mode:'fill',gap:20,outer_border:20,border_color:'#ffffff',gap_inches:0.1,outer_border_inches:0.2};
const state = {images:[{path:'a.jpg'},{path:'b.jpg'}],diptychs:[{image1:{path:'a.jpg',zoom:2.5,rotation:90,fit_mode:'fill',crop_focus:[0.2,0.8]},image2:{path:'b.jpg',fit_mode:'fit',zoom:0.7},config}],activeDiptychIndex:0,measurementUnit:'mm',libraryFilter:'placed',libraryQuery:'study',previewRequestSeq:100};
const raw = Workspace.serialize(state);
const restored = Workspace.read(raw,new Set(['a.jpg','b.jpg']),config);
assert.equal(restored.diptychs[0].image1.zoom,2.5);
assert.equal(restored.diptychs[0].image1.rotation,90);
assert.deepEqual(restored.diptychs[0].image1.crop_focus,[0.2,0.8]);
assert.equal(restored.diptychs[0].image2.zoom,0.7);
assert.equal(restored.measurementUnit,'mm');
assert.equal(restored.libraryFilter,'placed');
assert.equal(restored.libraryQuery,'study');
assert.equal(restored.previewRequestSeq,undefined);
const missing = Workspace.read(raw,new Set(['b.jpg']),config);
assert.equal(missing.images[0].missing,true);
assert.equal(missing.diptychs[0].image1.rotation,90);
restored.diptychs[0].image1.crop_focus[0]=1;
assert.equal(state.diptychs[0].image1.crop_focus[0],0.2);
function reject(change) { const data=JSON.parse(raw); change(data); assert.throws(()=>Workspace.read(JSON.stringify(data),new Set(),config)); }
reject(data=>data.version=99);
reject(data=>data.images.push({path:'a.jpg'}));
reject(data=>data.images[0].path='../secret.jpg');
reject(data=>data.diptychs[0].image1.path='unknown.jpg');
reject(data=>data.diptychs[0].config.width=0);
reject(data=>data.diptychs[0].config.gap_inches=6);
reject(data=>data.diptychs[0].image1.zoom=5);
reject(data=>data.diptychs[0].image1.crop_focus=[2,0]);
reject(data=>data.diptychs.push(data.diptychs[0]));
assert.equal(Workspace.read(null,new Set(),config),null);
const outside=JSON.parse(raw);outside.activeDiptychIndex=99;
assert.equal(Workspace.read(JSON.stringify(outside),new Set(),config).activeDiptychIndex,0);
console.log('Workspace recovery and validation checks passed');
