const assert = require('node:assert/strict');
const {create, pair} = require('../review_app/static/js/edit-history.js');
const h = create(2);
h.record({n:0}, {n:1}, 'Type', 'field');
h.record({n:1}, {n:2}, 'Type', 'field');
assert.deepEqual(h.undo(), {n:0});
assert.deepEqual(h.redo(), {n:2});
const state = {n:3};
h.record({n:2}, state, 'Place'); state.n=99;
assert.deepEqual(h.undo(), {n:2});
h.record({n:2}, {n:4}, 'New edit');
assert.equal(h.redo(), undefined);
h.record({n:4}, {n:4}, 'No-op');
assert.equal(h.undoLabel, 'New edit');
h.record({n:4}, {n:5}, 'Next');
h.record({n:5}, {n:6}, 'Final');
assert.deepEqual(h.undo(), {n:5});
assert.deepEqual(h.undo(), {n:4});
assert.equal(h.undo(), undefined);
const existing = [{image1:{path:'a',zoom:2.5,rotation:90,crop_focus:[0.2,0.8]},image2:{path:'b',fit_mode:'fit',zoom:0.7},config:{fit_mode:'fill',width:6,crop_focus:[0.3,0.4]}}];
const regrouped=pair([['b','a'],['c']],existing,{width:10});
assert.equal(regrouped[0].image2.zoom,2.5);
assert.equal(regrouped[0].image2.rotation,90);
assert.equal(regrouped[0].image2.fit_mode,'fill');
assert.deepEqual(regrouped[0].image1.crop_focus,[0.3,0.4]);
assert.equal(regrouped[0].image1.fit_mode,'fit');
assert.equal(regrouped[1].image2,null);
regrouped[0].image2.crop_focus[0]=1;
assert.equal(existing[0].image1.crop_focus[0],0.2);
assert.equal(pair([['a','b']],existing,{width:10})[0].config.width,6);
console.log('Edit history and framing preservation checks passed');
